<?php

/**
 * Userland PHP Generics
 *
 * @copyright Copyright 2026, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 *
 */
declare(strict_types=1);

namespace Lisachenko\Generics\StubGenerator;

/**
 * The banner every generated file carries
 *
 * A generated file that does not say so gets hand-edited, and the next run silently throws the
 * edit away. Saying it in the file is cheaper than explaining it afterwards.
 */
final class StubFileHeader
{
    public static function forStub(string $templateName): string
    {
        return sprintf(
            "<?php\n\n"
            . "/*\n"
            . " * GENERATED by bin/generics-stubs - do not edit.\n"
            . " *\n"
            . " * PHPStan stub for %s.\n"
            . " *\n"
            . " * The template declares its type parameter as a *native* type, which is what the\n"
            . " * engine keys substitution on and the opposite of what an analyser needs: PHPStan\n"
            . " * resolves that native type to an object type and lets it beat any @param tag. A stub\n"
            . " * replaces the declaration for analysis with the shape the class actually behaves\n"
            . " * like - mixed, with the doc tags carrying the meaning.\n"
            . " *\n"
            . " * One class per file, because PHPStan indexes only the first declaration in a stub.\n"
            . " * of() is written out rather than inherited, because stub files are reflected before\n"
            . " * the analysed paths are indexed and so cannot name the library's own traits.\n"
            . " */\n",
            $templateName,
        );
    }

    /**
     * @param list<string> $placeholderNames
     */
    public static function forPlaceholders(array $placeholderNames): string
    {
        $declarations = [];
        foreach ($placeholderNames as $name) {
            $position                 = strrpos($name, '\\');
            $namespace                = $position === false ? '' : substr($name, 0, $position);
            $shortName                = $position === false ? $name : substr($name, $position + 1);
            $declarations[$namespace] = [...$declarations[$namespace] ?? [], $shortName];
        }

        $blocks = [];
        foreach ($declarations as $namespace => $names) {
            $classes  = implode("\n", array_map(static fn(string $n): string => sprintf('class %s {}', $n), $names));
            $blocks[] = $namespace === '' ? $classes : sprintf("namespace %s;\n\n%s", $namespace, $classes);
        }

        return sprintf(
            "<?php\n\n"
            . "/*\n"
            . " * GENERATED by bin/generics-stubs - do not edit.\n"
            . " *\n"
            . " * The placeholder types the templates name in their declarations. They never exist at\n"
            . " * run time - that is the whole point, since an undefined class name is what gives the\n"
            . " * engine something to substitute - but PHPStan has to resolve them to analyse the\n"
            . " * files at all. Point parameters.scanFiles at this file.\n"
            . " */\n\ndeclare(strict_types=1);\n\n%s\n",
            implode("\n\n", $blocks),
        );
    }
}
